<a href="https://colab.research.google.com/github/RahmankhanA/Artificial-Nueral-Network-using-Keras/blob/main/Creating_ANN_Using_Keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Part 1***

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


# ***Loading Dataset***

In [ ]:
dataset=pd.read_csv('Churn_Modelling.csv')
dataset.head()


In [ ]:
dataset.info()

In [ ]:
X=dataset.iloc[:,3:13]
y=dataset.iloc[:,13]

# ***Create Dummy Variables***

In [ ]:
geography=pd.get_dummies(X["Geography"],drop_first=True)
gender=pd.get_dummies(X["Gender"],drop_first=True)

# ***Add Them to the Dataset***

In [ ]:
X=pd.concat([X,geography,gender], axis=1)

# ***Drop Unwanted Columns***

In [ ]:
X=X.drop(['Geography', 'Gender'],axis=1)

# ***Splitting Dataset into Train and Test***

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.25, random_state=0)

# ***Feature Scaling***

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)

# ***Part 2 -  Now lets make the ANN***

In [ ]:
# Importing Library and package
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LeakyReLU, PReLU,ELU
from keras.layers import Dropout

In [ ]:
# Initialising the ANN
classifier=Sequential()

In [ ]:
# Adding the input layer and first hidden layer
classifier.add(Dense(units=10, kernel_initializer='he_normal', activation='relu', input_dim=11))
classifier.add(Dropout(0.3))

In [ ]:
# Adding the second hidden layer
classifier.add(Dense(units=15, kernel_initializer='he_normal', activation='relu'))
classifier.add(Dropout(0.4))

In [ ]:
# Adding the third hidden layer
classifier.add(Dense(units=20, kernel_initializer='he_normal', activation='relu'))
classifier.add(Dropout(0.2))

In [ ]:
# Adding the output layer 
classifier.add(Dense(units=1, kernel_initializer='glorot_normal', activation='sigmoid'))

In [ ]:
classifier.summary()

In [ ]:
# compiling the ANN
classifier.compile(optimizer='adam', loss='binary_crossentropy',  metrics=['accuracy'])

In [ ]:
model_history=classifier.fit(X_train,y_train, validation_split=0.33, batch_size=10,   epochs=200)

**Predicting the test result**

In [ ]:
y_pred= classifier.predict(X_test)
y_pred=(y_pred > 0.5)

*Making Confusion Matrix*

In [ ]:
from sklearn.metrics import confusion_matrix

cm =confusion_matrix(y_test,y_pred)
cm

***Calculating the accuracy***

In [ ]:
from sklearn.metrics import accuracy_score
score= accuracy_score(y_test,y_pred)
score

In [ ]:
# uniform 
# array([[1894,   97],
#        [ 240,  269]])    0.8652

# normal 
#array([[1882,  109],
      #  [ 286,  223]])      0.842
# adding dropout
# array([[1928,   63],
#        [ 291,  218]])         0.8584
